name: fruit_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #core
  flutter_riverpod: ^2.3.6
  equatable: ^2.0.5
  kartal: ^2.8.0
  get_it: ^7.6.0
  flutter_svg: ^2.0.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/

  fonts:
    - family: BrandonGrotesque
      fonts:
        - asset: assets/fonts/BrandonGrotesque-Regular.ttf
        - asset: assets/fonts/BrandonGrotesque-Bold.ttf
          weight: 700
